# Generated by Django 4.2.14 on 2024-09-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hoursepower', models.FloatField()),
                ('price', models.FloatField()),
                ('carimage', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
